spring:
  application:
    name: limits-service
  cloud:
    config:
      enabled: true
  config:
    import: configserver:http://localhost:8888
#    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

limits-service:
  minimum: 2
  maximum: 998