spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8100

exchange-service:
  host: ''
#  host: http://localhost:8000
  path: /currency-exchange/from/{from}/to/{to}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
  service:
    name: ${spring.application.name}
