version: '3.7'

services:

  #  docker run -d -p 9411:9411 openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin
    ports: ["9411:9411"]
    networks:
      currency-network:
    environment:
      RABBIT_QUEUE: zipkin
      RABBIT_ADDRESSES: rabbit-mq:5672
      RABBIT_PASSWORD: rabbit_password
      RABBIT_USER: rabbit_user
    depends_on:
      - rabbit-mq
    restart: always

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_password
    networks:
      currency-network:

  naming-server:
    image: artarkatesoft/art-in28m-naming-server:${MICROSERVICES_IMAGE_VERSION}
    mem_limit: 700m
    ports:
      - 8761:8761
    networks:
      currency-network:

  #  docker container run -d -p 8000:8000 artarkatesoft/art-in28m-currency-exchange-service:0.0.1-SNAPSHOT
  currency-exchange:
    image: artarkatesoft/art-in28m-currency-exchange-service:${MICROSERVICES_IMAGE_VERSION}
    ports:
      - 8000:8000
    environment:
      "eureka.client.service-url.defaultZone": http://naming-server:8761/eureka
      "spring.zipkin.sender.type": rabbit
      "spring.rabbitmq.host": rabbit-mq
      "spring.rabbitmq.username": rabbit_user
      "spring.rabbitmq.password": rabbit_password

    depends_on:
      - naming-server
      - zipkin
      - rabbit-mq
    networks:
      currency-network:

  #  docker container run -d -p 8100:8100 artarkatesoft/art-in28m-currency-conversion-service:0.0.1-SNAPSHOT
  currency-conversion:
    image: artarkatesoft/art-in28m-currency-conversion-service:${MICROSERVICES_IMAGE_VERSION}
    ports:
      - 8100:8100
    environment:
      "eureka.client.service-url.defaultZone": http://naming-server:8761/eureka
      "spring.zipkin.sender.type": rabbit
      "spring.rabbitmq.host": rabbit-mq
      "spring.rabbitmq.username": rabbit_user
      "spring.rabbitmq.password": rabbit_password
    depends_on:
      - naming-server
      - currency-exchange
      - zipkin
      - rabbit-mq
    networks:
      currency-network:

  #  docker container run -d -p 8765:8765 artarkatesoft/art-in28m-api-gateway:0.0.1-SNAPSHOT
  api-gateway:
    image: artarkatesoft/art-in28m-api-gateway:${MICROSERVICES_IMAGE_VERSION}
    ports:
      - 8765:8765
    environment:
      "eureka.client.service-url.defaultZone": http://naming-server:8761/eureka
      "spring.zipkin.sender.type": rabbit
      "spring.rabbitmq.host": rabbit-mq
      "spring.rabbitmq.username": rabbit_user
      "spring.rabbitmq.password": rabbit_password
    depends_on:
      - naming-server
      - currency-exchange
      - currency-conversion
      - zipkin
      - rabbit-mq
    networks:
      currency-network:

networks:
  currency-network:
